org: cantoslucas
app: websocket-game
service: websocket-game

provider:
  name: aws
  runtime: python3.9

plugins:
  - serverless-offline

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get

      - websocket:
          route: hello
          routeResponseSelectionExpression: $default

  connection:
    handler: handler.connection
    events:
      - websocket: 
          route: $connect
      - websocket:
          route: $disconnect
    